export const OPEN_CHAT_MODES = Object.freeze({
  DIRECT_CHAT: 'DIRECT_CHAT',
  REACT_AGENT: 'REACT_AGENT',
  PLAN_AND_EXECUTE: 'PLAN_AND_EXECUTE'
})

export const DEFAULT_OPEN_CHAT_MODE = OPEN_CHAT_MODES.DIRECT_CHAT
